### ISSUE TITLE
Specifying the default linefly theme

### ISSUE THREAD

**Issue by qbnil** [bluz71/nvim-linefly#15]
Is there any way i can set the default colorscheme in the linefly file config, because the whole is messed up unless i change the current neovim theme manually, well, using fzf-lua actually:
before: 
![image](https://github.com/bluz71/nvim-linefly/assets/130576530/c4c12aea-e3d5-467d-806a-9ffa3520230c)
after:
![image](https://github.com/bluz71/nvim-linefly/assets/130576530/7ed8079b-541f-4b45-aafe-1e96eaa89008)
Here's my current config for the linefly: 
![image](https://github.com/bluz71/nvim-linefly/assets/130576530/5bf9f91d-13ec-423a-8252-f0a19d082576)
i tried it with lazy = false and priority = 1000, it hasn't help

**Comment by bluz71** [comment]
Do not lazy load _linefly_ statusline, please delete `event = 'VeryLazy'`.

This plugin is **not** designed to be lazy-loaded as mentioned in the [installation instructions](https://github.com/bluz71/nvim-linefly?tab=readme-ov-file#installation).

Not all plugins can be lazy-loaded.
