### ISSUE TITLE
bug: strange flicker and also disappears when entering insert mode

### ISSUE THREAD

**Issue by windowsrefund** [bluz71/nvim-linefly#16]
Hello.

I love the look of this plugin and am about 10m into using it so I may not have all the information needed to correctly identify what's happening. Here's a bit of information about my environment.

neovim version: 0.10.0
terminal; Alacritty
nvim-linefly config: default lazy install

Here's a short list of what I can reproduce:

1. Open any file. Statusline appears and looks normal.
2. Press `i` to enter insert mode. Statusline completely disappears.
3. Press `Esc`. Statusline reappears.
4. I can keep reproducing this sequence of events pressing  `i` and `Esc` in order to show and hide the Statusline.
5. Press `o` in order to enter insert mode below the current line. Statusline changes mode to `insert` correctly.
6. Press `Esc` to go back to normal mode. Statusline behaves as expected and changes mode back to `normal`.
7. Press `dd` to delete now empty line. Statusline flickers.

Please let me know if there's anything more useful I can provide. Thanks in advance.

**Comment by bluz71** [comment]
Please provide me a minimal `lazy.lua` file that reproduces the issue. Strip away every plugin except `linefly` to reproduce the issue.

Please also make sure that `linefly` is installed as follows in `lazy.lua`:

```lua
{ 'bluz71/nvim-linefly' },
```

Do not use any form of lazy-loading.

Note, I use Neovim `0.10` with Alacritty and `Lazy` without the issues you describe.

Best regards.

**Comment by bluz71** [comment]
Hello @windowsrefund,

Any further news with regard to your issue?

**Comment by windowsrefund** [comment]
Yes, with a minimal lazy setup, I've been unable to reproduce what I wrote above so it's clear to me 1 or more of my plugins is responsible for what I had previously reported. I'll get busy hunting that @%!! down as I really like this statusline and am looking forward to using it. Thanks for the suggestion to minimize as that was clearly the move.

**Comment by bluz71** [comment]
Hello @windowsrefund,

When you discover the root cause please let me know about it, I am interested in understanding this issue in case other people encounter the same problem. Also, there may be a possibility I could work around it (though that is only a small possibility).

Good luck in your hunting, and let me know how it goes.

Best regards.
