### ISSUE TITLE
Text unreadable with falcon colorscheme

### ISSUE THREAD

**Issue by marcelmanz** [bluz71/nvim-linefly#17]
I use this colorscheme: https://github.com/fenetikm/falcon

And the text on the status line seems too gray in the vim mode area. Is there a way to update that highlight to be darker?

Screenshot:
![2024-07-26-185545_hyprshot](https://github.com/user-attachments/assets/9866fc6c-1f11-480e-b904-c7b0a318f9ae)

Thanks!

**Comment by bluz71** [comment]
Support has now been added for the `falcon` colorscheme.

It should look much better now.

Best regards.
