### ISSUE TITLE
[BUG] nvim-dap-ui window names

### ISSUE THREAD

**Issue by serranomorante** [bluz71/nvim-linefly#8]
Thank you so much for this plugin!

## Description

nvim-dap-ui windows lose their original names

![image](https://github.com/bluz71/nvim-linefly/assets/43413954/c709d457-3202-4ad3-81fa-35102dccd43b)

![image](https://github.com/bluz71/nvim-linefly/assets/43413954/d07976b2-944c-49c5-a64c-8ede81cb6af9)

## Reproducible steps

```lua
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = "/tmp/nvim-debug-issue/" .. name
end

vim.g.mapleader = " "

local plugins = {
  {
    "rcarriga/nvim-dap-ui",
    dependencies = "mfussenegger/nvim-dap",
    lazy = false,
    keys = {
      {
        "<leader>du",
        function() require("dapui").toggle() end,
        desc = "Toggle Debugger UI",
      },
    },
    config = true,
  },

  {
    "bluz71/nvim-linefly",
    enabled = true
  },
}

--------------------------------------------------------------------------------

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)
require("lazy").setup(plugins)
```

1. copy the previous snippet in a file, lets say `debug-issue.lua`
2. open with `nvim --clean +'so debug-issue.lua'`. Don't worry, it won't mess up with your home directory (see line 2)
3. press `<leader>du` to bring the nvim-dap-ui windows

You will notice the issue with window names

(then, if you change `enabled = false` on line 24 you will see the window names as expected)

btw, I love that this plugin renames the tabs to Tab:1 💖 nice touch!

**Comment by bluz71** [comment]
Thanks for the detailed report.

I have now added in support for [nvim-dap-ui](https://github.com/rcarriga/nvim-dap-ui) including handling these cases:

- Global statusline, `set laststatus=3`, with linefly `winbar` option enabled.
- And, normal statusline, `set laststatus=2`, with linefly `winbar` option disabled.

Let me know how if you have any issues since I only carried out basic tests.

**Comment by serranomorante** [comment]
Working great! Thanks 💖
