### ISSUE TITLE
Add `showcmd` to the statusline.

### ISSUE THREAD

**Issue by rafaelcl292** [bluz71/nvim-linefly#9]
Add `showcmd` to the statusline potentially when `showcmdloc=statusline`.

I noticed in #5 this functionality was mentioned, but it does not show up in when i load the plugin.

**Comment by bluz71** [comment]
At the time I did not feel it warranted the development cost. I assumed nobody cared.

However, I will revisit again. It is probably quite easy to integrate. Give me a couple days.

Thanks.

**Comment by bluz71** [comment]
I have implemented `showcmd` support.

Please use Neovim `0.9` or later and set both `set showcmdloc=statusline` and `set showcmd`. The `showcmd` content will be displayed in the right-hand side area (inside the linenumber section).

Hopefully it works well for you.

Best regards.

**Comment by rafaelcl292** [comment]
It works perfectly.
Appreciate it!
